// ─────────────────────────────────────────────────────────────────────────────
// importMT5History.js
//
// Imports MT5 historical OHLC bars from DWX_History_Export.json
// (generated by ExportHistory.mq5) into price_feed_history table.
//
// Each M1 bar is expanded into 4 synthetic ticks (O, H, L, C) so the
// existing candle-bucketing query in trades.js can reconstruct proper
// OHLC candles at any timeframe (1M, 5M, 15M, 1H, 4H, 1D).
//
// Usage:
//   node importMT5History.js
//
// The script will:
//   1. Read DWX_History_Export.json from your DWX_PATH folder
//   2. Clear existing history for each imported symbol
//   3. Bulk-insert all ticks in batches of 1000 (fast — handles 100k+ rows)
//   4. Update PRICE_HISTORY_RETAIN_DAYS in your .env to match imported range
// ─────────────────────────────────────────────────────────────────────────────
require('dotenv').config()
const { Pool } = require('pg')
const fs = require('fs')
const path = require('path')

const pool = new Pool({ connectionString: process.env.DATABASE_URL })

const DWX_PATH    = process.env.DWX_PATH
const EXPORT_FILE = path.join(DWX_PATH, 'DWX_History_Export.json')

// Default spreads per instrument (used if bar.s is missing)
const DEFAULT_SPREADS = {
  EURUSD: 0.00012,
  GBPUSD: 0.00014,
  XAUUSD: 0.30,
  XAGUSD: 0.03,
}

// Bulk insert rows in batches to avoid hitting PostgreSQL parameter limits (~65k)
// Each tick has 4 params → batch of 1000 ticks = 4000 params (safe)
const BATCH_SIZE = 1000

async function bulkInsert(client, rows) {
  if (rows.length === 0) return

  // Build: INSERT INTO price_feed_history (instrument, bid, ask, recorded_at) VALUES ($1,$2,$3,$4), ($5,...) ...
  const values = []
  const placeholders = rows.map((row, i) => {
    const base = i * 4
    values.push(row.instrument, row.bid, row.ask, row.recorded_at)
    return `($${base + 1}, $${base + 2}, $${base + 3}, to_timestamp($${base + 4} / 1000.0))`
  })

  await client.query(
    `INSERT INTO price_feed_history (instrument, bid, ask, recorded_at)
     VALUES ${placeholders.join(',')}
     ON CONFLICT DO NOTHING`,
    values
  )
}

async function main() {
  console.log('=== MT5 History Importer ===\n')

  // ── 1. Check export file exists ──────────────────────────────────
  if (!fs.existsSync(EXPORT_FILE)) {
    console.error('✗ Export file not found:', EXPORT_FILE)
    console.error('')
    console.error('  Steps to generate it:')
    console.error('  1. Copy ExportHistory.mq5 to MT5 → MQL5 → Scripts')
    console.error('  2. Compile it in MetaEditor (F7)')
    console.error('  3. Drag it onto any MT5 chart')
    console.error('  4. Check Experts tab for the output path')
    console.error('  5. Re-run this script')
    process.exit(1)
  }

  console.log('✓ Found:', EXPORT_FILE)

  // ── 2. Parse JSON ────────────────────────────────────────────────
  let data
  try {
    const raw = fs.readFileSync(EXPORT_FILE, 'utf8')
    data = JSON.parse(raw)
  } catch (err) {
    console.error('✗ Failed to parse export file:', err.message)
    process.exit(1)
  }

  const symbols = Object.keys(data)
  if (symbols.length === 0) {
    console.error('✗ Export file contains no symbols')
    process.exit(1)
  }

  console.log('  Symbols found:', symbols.join(', '))

  // ── 3. Connect to DB ─────────────────────────────────────────────
  try {
    await pool.query('SELECT 1')
    console.log('✓ Database connected\n')
  } catch (err) {
    console.error('✗ Database connection failed:', err.message)
    process.exit(1)
  }

  const client = await pool.connect()
  let totalInserted = 0
  let earliestTs = Infinity

  try {
    await client.query('BEGIN')

    for (const [symbol, candles] of Object.entries(data)) {
      if (!Array.isArray(candles) || candles.length === 0) {
        console.log(`  ⚠  ${symbol}: no bars — skipping`)
        continue
      }

      // Clear existing data for this symbol so we don't double-count
      const deleted = await client.query(
        'DELETE FROM price_feed_history WHERE instrument = $1',
        [symbol]
      )
      console.log(`  ${symbol}: cleared ${deleted.rowCount} existing rows`)

      const spread = DEFAULT_SPREADS[symbol] || 0.00012
      let batch = []
      let count = 0

      for (const bar of candles) {
        if (!bar.t || !bar.o) continue // skip malformed bars

        const baseMs  = bar.t * 1000
        const barSpread = bar.s || spread

        // Track earliest timestamp for PRICE_HISTORY_RETAIN_DAYS suggestion
        if (bar.t < earliestTs) earliestTs = bar.t

        // Expand 1 OHLC bar → 4 synthetic ticks (O at t+0, H at t+15s, L at t+30s, C at t+59s)
        // This preserves OHLC fidelity when the candle endpoint re-buckets by timeframe
        const ticks = [
          { instrument: symbol, bid: bar.o, ask: bar.o + barSpread, recorded_at: baseMs },
          { instrument: symbol, bid: bar.h, ask: bar.h + barSpread, recorded_at: baseMs + 15000 },
          { instrument: symbol, bid: bar.l, ask: bar.l + barSpread, recorded_at: baseMs + 30000 },
          { instrument: symbol, bid: bar.c, ask: bar.c + barSpread, recorded_at: baseMs + 59000 },
        ]

        for (const tick of ticks) {
          batch.push(tick)
          count++

          if (batch.length >= BATCH_SIZE) {
            await bulkInsert(client, batch)
            batch = []
            process.stdout.write(`\r  ${symbol}: ${count} ticks inserted...`)
          }
        }
      }

      // Flush remaining
      if (batch.length > 0) {
        await bulkInsert(client, batch)
      }

      totalInserted += count
      console.log(`\r  ✓ ${symbol}: ${candles.length} bars → ${count} ticks inserted`)
    }

    await client.query('COMMIT')

    // ── 4. Report results ─────────────────────────────────────────
    const daysImported = earliestTs < Infinity
      ? Math.ceil((Date.now() / 1000 - earliestTs) / 86400)
      : 0

    console.log('')
    console.log('═══════════════════════════════════════════════')
    console.log(`✓ Import complete!`)
    console.log(`  Total ticks inserted : ${totalInserted.toLocaleString()}`)
    console.log(`  History span         : ~${daysImported} days`)
    console.log('')
    console.log('  ACTION REQUIRED — update your .env:')
    console.log(`  PRICE_HISTORY_RETAIN_DAYS=${daysImported + 7}`)
    console.log('')
    console.log('  Then restart your backend server.')
    console.log('  Charts will immediately show full MT5 history.')
    console.log('═══════════════════════════════════════════════')

  } catch (err) {
    await client.query('ROLLBACK')
    console.error('\n✗ Import failed:', err.message)
    console.error(err.stack)
  } finally {
    client.release()
    await pool.end()
  }
}

main()
