import React from 'react'
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BarChart2,
  Bell,
  BookOpen,
  Calendar,
  CheckCircle,
  CheckCircle2,
  Clock,
  Clock3,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Filter,
  Headset,
  Info,
  KeyRound,
  LayoutDashboard,
  LogOut,
  MessageCircle,
  Minus,
  MoreHorizontal,
  Moon,
  Pencil,
  Plus,
  Repeat2,
  ScanFace,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  Sun,
  Target,
  TimerReset,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  Users,
  Wallet,
  X,
  XCircle,
} from 'lucide-react'

const ICON_MAP = {
  dashboard: LayoutDashboard,
  rules: BookOpen,
  trade: TrendingUp,
  analytics: BarChart2,
  history: Clock,
  leaderboard: Trophy,
  journal: BookOpen,
  calendar: Calendar,
  support: MessageCircle,
  settings: Settings,
  logout: LogOut,
  users: Users,
  trades: Activity,
  payouts: CreditCard,
  'audit-log': Shield,
  'risk-alerts': AlertTriangle,
  kyc: Shield,
  funded: Trophy,
  challenges: Trophy,
  chat: MessageCircle,
  dispute: AlertTriangle,
  copier: Repeat2,
  violations: AlertTriangle,
  search: Search,
  edit: Pencil,
  delete: Trash2,
  approve: CheckCircle,
  reject: XCircle,
  copy: Copy,
  info: Info,
  warning: AlertTriangle,
  download: Download,
  filter: Filter,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  activity: Activity,
  balance: DollarSign,
  floating_up: TrendingUp,
  floating_down: TrendingDown,
  drawdown: ShieldAlert,
  target: Target,
  buy: TrendingUp,
  sell: TrendingDown,
  close: X,
  plus: Plus,
  minus: Minus,
  profile: User,
  message: MessageCircle,
  key: KeyRound,
  lock: Shield,
  flag: AlertTriangle,
  command: Shield,
  tenant: Copy,
  pnl: Activity,
  menu: MoreHorizontal,
  file: FileText,
  folder: FileText,
  selfie: ScanFace,
  timer: TimerReset,
  wallet: Wallet,
  badgeCheck: CheckCircle2,
  repeat: Repeat2,
  x: X,
  arrow: ArrowRight,
  '📊': BarChart2,
  '📈': TrendingUp,
  '📋': FileText,
  '🧠': BarChart2,
  '🪪': Shield,
  '💰': DollarSign,
  '💬': MessageCircle,
  '⚖️': AlertTriangle,
  '🎧': Headset,
  '🔍': Search,
  '🔔': Bell,
  '✅': CheckCircle2,
  '❌': XCircle,
  '⚠️': AlertTriangle,
  '🏆': Trophy,
  '💸': CreditCard,
  '🚩': AlertTriangle,
  '✉️': MessageCircle,
  '🔑': KeyRound,
  '🚫': XCircle,
  '📥': Download,
  '⬇': Download,
  'ℹ️': Info,
  '🚨': AlertTriangle,
  '🔁': Repeat2,
  '📝': BookOpen,
  '＋': Plus,
  '✕': X,
  '×': X,
  '⏳': Clock3,
  '🔒': Shield,
  '📁': FileText,
  '📄': FileText,
  '🤳': ScanFace,
  '🎯': Target,
  '🛑': ShieldAlert,
  '💥': TrendingDown,
  '📭': FileText,
  '📉': TrendingDown,
  '⏰': Clock3,
  '🚀': TrendingUp,
  '🏠': LayoutDashboard,
  '👤': User,
  '💳': CreditCard,
  '🛡': Shield,
  '🗑': Trash2,
  '✏': Pencil,
  '📅': Calendar,
  '🕒': Clock3,
  '📨': MessageCircle,
  '⚡': Activity,
}

export function renderIcon(icon, options = {}) {
  const {
    size = 16,
    color,
    strokeWidth = 2,
    style,
    className,
  } = options

  if (React.isValidElement(icon)) {
    return React.cloneElement(icon, {
      size: icon.props.size ?? size,
      color: icon.props.color ?? color,
      strokeWidth: icon.props.strokeWidth ?? strokeWidth,
      className: [icon.props.className, className].filter(Boolean).join(' ') || undefined,
      style: { ...(style || {}), ...(icon.props.style || {}) },
    })
  }

  const IconComponent = ICON_MAP[icon]
  if (!IconComponent) return icon || null

  return (
    <IconComponent
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
    />
  )
}

